### ISSUE TITLE
path_length

### ISSUE THREAD

**Issue by FabienRech** [qurit/rt-utils#71]
Hi, 
I was wondering if there is a potential limit to the length of the path directory used by the RTStrcuctBuilder.create_from() ?

I have created a script which was working well but as I lauched it on  a new computer (and adapted the path) it did not work...I had no space or special caractere in my path. 

The only solution I have found was to change the path by reducing it a little bit ?

Do you have an explanation ? 

Best

Fabien

**Comment by awtkns** [comment]
HI @FabienRech, I have run into this issue before when working with dicom structures. Assuming you are using windows there is limitation of 260 characters the path length in the files systems. More details can be found [here](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry).

> The Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters. A local path is structured in the following order: drive letter, colon, backslash, name components separated by backslashes, and a terminating null character. For example, the maximum path on drive D is "D:\some 256-character path string<NUL>" where "<NUL>" represents the invisible terminating null character for the current system codepage. (The characters < > are used here for visual clarity and cannot be part of a valid path string.)

This the is no restriction in RT-utils on path length. I am going close this ticket for now as it seems this an issue outside of rt-utils. Please feel free to re-open if you see otherwise.

**Comment by FabienRech** [comment]
Thank you for your answer. I just want to complete my issue. 
In fact my path length was only 180 characters, it is the reason why I asked you that because I have made research and found this 260 characters limitation on windows. 
Moreover the issue was really weird because the output was "No DICOM images found in the input path". And as I said it before, I had performed the same analysis on the same folder and file before without problem. And by just changing the path, the script was able to find the dicom file inside the folder.
